# Generated by Django 4.2.5 on 2023-09-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.IntegerField(max_length=10)),
                ('confrm_password', models.IntegerField(max_length=10)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
