# Generated by Django 4.2.5 on 2023-09-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registers',
            name='confrm_password',
        ),
    ]
