# Generated by Django 4.2.5 on 2023-09-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0002_remove_registers_confrm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='name',
            field=models.CharField(default='nemo', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registers',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
