# Generated by Django 4.2.5 on 2023-09-23 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0003_registers_name_alter_registers_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('borrowed', models.BooleanField(default=False)),
                ('borrowd_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admn.registers')),
            ],
        ),
    ]
