# Generated by Django 4.2.5 on 2023-09-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0004_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='books',
        ),
    ]
