# Generated by Django 4.2.5 on 2023-09-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0006_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='borrowd_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admn.registers'),
        ),
    ]
