# Generated by Django 4.2.5 on 2023-09-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0007_alter_books_borrowd_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='borrowed',
            new_name='is_borrowed',
        ),
    ]
