# Generated by Django 4.2.5 on 2023-09-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0008_rename_borrowed_books_is_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='borow_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='retrn_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
