# Generated by Django 4.2.5 on 2023-09-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0009_books_borow_dt_books_retrn_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='borow_dt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='is_borrowed',
            field=models.CharField(choices=[('TRUE', 'true'), ('FALSE', 'false')], default='FALSE'),
        ),
    ]
