# Generated by Django 4.2.5 on 2023-09-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0014_alter_books_retrn_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='retrn_dt',
            field=models.CharField(choices=[('saturday', 'saturday'), ('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday')], null=True),
        ),
    ]
