# Generated by Django 4.2.5 on 2023-09-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0015_alter_books_retrn_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='borow_dt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
