# Generated by Django 4.2.5 on 2023-09-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0017_alter_books_is_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='borow_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
